### ISSUE TITLE
How to create nested validations

### ISSUE THREAD

**Issue by iagomelanias** [19majkel94/type-graphql#195] opened 2018-11-13 00:35 UTC
**Describe the issue**
Hello! 👋
I'm trying to validated `InputType`. A specific field has it's own type. It looks like above:
```ts
@InputType()
export class RecipeInput {
  @Field()
  @Type(() => AuthorInput)
  author: AuthorInput;
}
```

The `CustomerInput` looks like this:
```ts
@InputType()
export class AuthorInput {
  @Field()
  @Length(1, 255)
  firstName: string;
}
```
TypeGraphQL builds the schema correctly, but `class-transformer` does not validate the nested input. I also tried to add the `@ValidateNested` decorator, but i get the following error:
```
"constraints": {
  "nestedValidation": "nested property customer must be either object or array"
}

Error: Argument Validation Error,
  at Object.<anonymous> (/Users/iago/Drive/Code/api/node_modules/type-graphql/resolvers/validate-arg.js:21:19),
  at Generator.throw (<anonymous>),
  at rejected (/Users/iago/Drive/Code/api/node_modules/tslib/tslib.js:105:69),
  at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I found a [test case](https://github.com/19majkel94/type-graphql/blob/66e7f9789097a58a96d7eaeb5472fb539632fba4/tests/functional/fields.ts#L25-L28) which contains a nested input type, but i didn't find any test case using validations.

As mentioned in [this comment](https://github.com/19majkel94/type-graphql/issues/133#issuecomment-415962812), it looks like the nested object is not converted to `AuthorInput` class, the property `author` is `[Object: null prototype]`.

So, with the current limitations, is there any way to implement a nested validation?

**Are you able to make a PR that fix this?**
I don't think so, but i can add some test cases to ensure this is properly covered.

**Additional context**
* TypeGraphQL Version: 0.15.0
* Node Version: v11.1.0

**Comment by 19majkel94** [comment] 2018-11-13 12:18
The test case is only for schema generation, not for runtime instance check nor nested validation (unfortunately). 

So closing this as duplicate of #133 🔒

As a temporary workaround you need to perform the validation manually in resolvers, I think that [`class-transformer-validator`](https://github.com/19majkel94/class-transformer-validator) would be the best (one-liner).

**Closed by 19majkel94** 2018-11-13 12:18 UTC
Labels: Duplicate :key:, Question :grey_question:
