### ISSUE TITLE
formatArgumentValidationError doesn't align to apollo formatError

### ISSUE THREAD

**Issue by galkin** [19majkel94/type-graphql#259] opened 2019-02-23 09:57 UTC
**Describe the bug**
formatArgumentValidationError doesn't align to apollo formatError

**To Reproduce**
1. Install the lastest dependencies versions:
```
npm install apollo-server-core type-graphql typescript
+ apollo-server-core@2.4.6
+ typescript@3.3.3333
+ type-graphql@0.16.0
```
2. Create file `index.ts` with such content
```
import { Config } from 'apollo-server-core';
import { formatArgumentValidationError } from 'type-graphql';

const options: Config = {
  formatError: formatArgumentValidationError
};
```
3. Run compiling
```
tsc index.ts
index.ts:5:3 - error TS2322: Type '(err: GraphQLError) => { [key: string]: any; }' is not assignable to type '(error: GraphQLError) => GraphQLFormattedError'.
  Type '{ [key: string]: any; }' is missing the following properties from type 'GraphQLFormattedError': message, locations, path

5   formatError: formatArgumentValidationError
    ~~~~~~~~~~~

  node_modules/apollo-server-core/dist/graphqlOptions.d.ts:10:5
    10     formatError?: (error: GraphQLError) => GraphQLFormattedError;
           ~~~~~~~~~~~
    The expected type comes from property 'formatError' which is declared here on type 'Config'


Found 1 error.
```
**Expected behavior**
Code compiled without errors

**Enviorment (please complete the following information):**
 - OS: Mac
 - Node v10.15.1
 - Package version 0.16.0
 - TypeScript version 3.3.3333

**Comment by 19majkel94** [comment] 2019-02-23 10:00
Duplicate of #258 🔒

**Closed by 19majkel94** 2019-02-23 10:00 UTC
