### ISSUE TITLE
More specific error message when Root Query missing

### ISSUE THREAD

**Issue by AleffSouza** [19majkel94/type-graphql#218] opened 2018-12-27 18:00 UTC
**Describe the bug**
A server only with one mutation generates a "Generating schema error"

**To Reproduce**
Create a server with nothing more than one mutation:

```
import "reflect-metadata";
import { ApolloServer } from "apollo-server";
import { buildSchema, ObjectType, Field, Resolver, Arg, Mutation } from "type-graphql";

@ObjectType()
class Hello {
  @Field()
  message: string;
}

@Resolver(of => Hello)
class HelloResolver {
  @Mutation(returns => Hello)
  sayHello(@Arg('name') name: string) {
    return {
      message: `Hello ${name}`
    }
  }
} 

async function bootstrap() {
  try {
    const schema = await buildSchema({
      resolvers: [
        HelloResolver
      ],
      emitSchemaFile: true
    });
    
    const server = new ApolloServer({
      schema,
      playground: true,
    });
    
    await server.listen();
  } catch (err) {
    console.log(`Err: ${err}`)
  }
}

bootstrap();
```

**Expected behavior**
A more specific error message. (i.e the graphql package returns 'Query root type must be provided.')

**Enviorment (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6
 - Node v11.3.0
 - Package version 0.16.0

**Comment by 19majkel94** [comment] 2018-12-27 18:08
@AleffSouza 
You can read the detailed info in `details` property. `graphql-js` returns an array of `GraphQLError`, so the `GeneratingSchemaError` wraps them into one error object.

The cause of the error is not on TypeGraphQL side but on `graphql-js`, like you sad `Query root type must be provided.`.

**Comment by 19majkel94** [comment] 2019-01-02 17:58
Closing in favor of related all-in-one issue #12 🔒

**Closed by 19majkel94** 2019-01-02 17:58 UTC
Labels: Community  :family_man_girl:, Enhancement :new:
