### ISSUE TITLE
Typescript module and type-graphql dependency

### ISSUE THREAD

**Issue by fromnowhereuser** [19majkel94/type-graphql#69] opened 2018-04-23 21:28 UTC
I love your project. The approach seems to be very similar to the JAVA one. And i like that.

One domain model that make "one source of truth". Then i have splitted my TS class model definition in a specific node project (the library) to make it available from:

a type-graphql server 
AND 
an Angular app.

The library project AND the type-graphql server depend of type-graphql.

When i launch the server, i have something like that:
Error: Cannot determine type for MyType:attr

Am i doing it wrong ? Because... it seems that type-graphql is enable to see the transpiled anotation. Thank you for any help or advice you can provide.

**Comment by 19majkel94** [comment] 2018-04-24 07:50
There's no need to use TypeGraphQL in Angular App. To fetch data from GraphQL server you write dedicated GraphQL queries. Then you can use `apollo-codegen` to generate interfaces describing the data that server return for this queries and you should use them in your component as the data type, not the model class.

**Comment by 19majkel94** [comment] 2018-04-29 17:47
Closing as `v0.11.2` has support for multi project/modules. 
@fromnowhereuser Please feel free to reopen this issue if you still have a problem with this.

**Comment by fromnowhereuser** [comment] 2018-04-30 10:57
@19majkel94 i dont need graphql form the angular project. But i want the class definitions. I use them a lot in the angular project.


Angular Project               ======\
                                                      =====> Models project  =====> Typegraphql (for annotations)
Typegraphql project       ======/


But it doesnt work. Do i did it wrong ?

**Comment by 19majkel94** [comment] 2018-04-30 11:49
Seems like you don't have `reflect-metadata` imported in your Angular app or your tsconfig.json doesn't have `"emitDecoratorMetadata": true,` options set. So when decorators are evaluated, they throw errors like `Cannot determine type for MyType:attr`.

I would have to create a dummy decorators that could be used in browser, like TypeORM:
https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js

**Comment by fromnowhereuser** [comment] 2018-04-30 15:25
i dont have any problem in my angular App. Again, i dont use typegraphql in my angular app, i just need the class.

My problem is when i want to start the typegraphql project. If i define the annotated class in a lib, the app wont start:
Error: Cannot determine type for MyType#name !
But if i define the annotated class directly in the typegraphql project its ok. But i need to use the entity in another project ( the angular one).

I'm really sorry if the explanation was not clear...

**Comment by 19majkel94** [comment] 2018-04-30 15:26
Please create a repository with minimal example code that reproduce the issue, so I could run it and find where the problem is 😉

**Comment by fromnowhereuser** [comment] 2018-05-02 15:32
Here the sample project:
https://github.com/fromnowhereuser/back

Just go to models2
npm install
tsc && npm link

and go to back
npm install
npm link models2
tsc && ./build/app.js

**Comment by fromnowhereuser** [comment] 2018-05-02 16:28
Wow..? that's a lot of error... Thank you very much for your support and time.

I have business functions on my types. I am building a progressive app... Every derived class (from XaItem) has business functions.

What do you think ?

**Comment by 19majkel94** [comment] 2018-05-03 09:32
> I have business functions on my types.

So seems you like OOP. But with this you volatile the single responsibility principle.

Use TypeGraphQL types like a DTO classes. Move the logic to separate services or create adapters for converting model classes (business logic, db entity stuffs, etc.) to DTO and vice-versa. Don't use big, all-in-one classes with multiple interfaces and inheritance chains 😉

**Comment by fromnowhereuser** [comment] 2018-05-03 11:40
So, one class representing Data only. And interface for specific behavior ? Seems good to me. Did i get it ?

**Comment by 19majkel94** [comment] 2018-05-03 14:47
Basically, yes 😉 

I am closing this issue for now.
If you have more question, please ask them on [the gitter channel](https://gitter.im/type-graphql/Lobby). Issues should be used for bug reports and feature requests. Thanks!

**Closed by 19majkel94** 2018-05-03 14:47 UTC
Labels: Needs More Info :man_shrugging:, Question :grey_question:
