### ISSUE TITLE
InputType field name

### ISSUE THREAD

**Issue by Nikamura** [19majkel94/type-graphql#346] opened 2019-05-28 16:48 UTC
**Describe the bug**

Name provided for input field will create a new variable instead of assigning to the correct one.

**To Reproduce**

```
@InputType()
export class C {
  @Field(_type => ObjectIdScalar, { name: "buildId" })
  public buildObjectId!: ObjectId;
}
```	

```
@Arg("input") input: C
```

`input.buildObjectId` will be undefined, while `input.buildId` will have input value.

**Expected behavior**

`input.buildObjectId` to have input value.

**Comment by 19majkel94** [comment] 2019-05-28 20:07
Duplicate of #263 🔒

**Closed by 19majkel94** 2019-05-28 20:07 UTC
