### ISSUE TITLE
Typing Multidimensional Array

### ISSUE THREAD

**Issue by RyannGalea** [19majkel94/type-graphql#376] opened 2019-07-12 13:33 UTC
I need to type some data that comes back from an API api as a Multidimensional Array, number[][][], I had assumed that I would type it as follows:

     @Field(type => [[[Int]]])
      rings: number[][][]

But it fails & L'm unsure of how to resolve.

**Comment by 19majkel94** [comment] 2019-07-12 13:36
Duplicate of #277 🔒

**Closed by 19majkel94** 2019-07-12 13:36 UTC
