### ISSUE TITLE
Cannot apply fragment on subscription

### ISSUE THREAD

**Issue by stevefan1999-personal** [19majkel94/type-graphql#159] opened 2018-09-27 16:07 UTC
**To Reproduce**
Just use a fragment on a subscription selection set.
```gql
fragment BookFragment on Book {
  isbn
  name
}

subscription {
  book_liked(book: "0-321-48681-1") {
    ...BookFragment
  }
}
```

```ts
 @Subscription(() => Book, {
    topics: 'BOOK_LIKED',
    name: 'book_liked',
    filter: ({ payload, args: { book } }: any) => payload && (!book || book === payload.isbn)
  })
  async onBookLiked (
    @Root() book: Book,
    @Arg('book', () => ID, { nullable: true }) _book?: string
  ): Promise<Book> {
    return book
  }
```

**Expected behavior**
The subscription should start to listen for any like event

**Actual behavior**
The subscription resolver was fired immediately without root value the moment I started listening for subscription, nor would it have any filter beforehand. Also the subscription will be unsubscribed immediately.

**Workaround**
You can do nothing but inline the fragment
```gql
subscription {
  book_liked(book: "0-321-48681-1") {
    isbn
    name
  }
}
```

**Comment by 19majkel94** [comment] 2018-09-27 20:46
Sorry but cannot reproduce. It doesn't look like `type-graphql` problem as I only delegate it to `graphql-subscriptions`:

```ts
it.only("should successfully get data from subscription using fragments", async () => {
  let subscriptionValue!: number;
  const testedValue = Math.PI;
  const subscriptionQuery = gql`
    fragment TestFragment on SampleObject {
      value
    }
    subscription {
      sampleTopicSubscription {
        ...TestFragment
      }
    }
  `;
  const mutation = gql`
    mutation {
      pubSubMutation(value: ${testedValue})
    }
  `;

  apollo.subscribe({ query: subscriptionQuery }).subscribe({
    next: ({ data }) => (subscriptionValue = data!.sampleTopicSubscription.value),
  });
  await apollo.mutate({ mutation });

  expect(subscriptionValue).toEqual(testedValue);
});
```
```
Functional
      √ should successfully get data from subscription using fragments (59ms)
```

**Comment by 19majkel94** [comment] 2018-09-28 17:32
Closing as it should be handled by `graphql-subscriptions` team:
https://github.com/apollographql/graphql-subscriptions/issues/178

@stevefan1999-personal
Try to reproduce the problem using only `graphql-subscriptions`, without TypeGraphQL.

**Closed by 19majkel94** 2018-09-28 17:32 UTC
Labels: Invalid :-1:

**Comment by elderapo** [comment] 2019-08-03 00:45
After some digging, I've found the issue.

Looks like `@Root` decorator does not work correctly with anonymous subscriptions. [Here](https://github.com/elderapo/type-graphql-subscription-bug) is small reproducible repo.

**Comment by elderapo** [comment] 2019-08-04 21:21
@19majkel94 I think this issue should be reopened.

**Comment by 19majkel94** [comment] 2019-08-08 09:50
No, It won't be reopened as it's still an error in `graphql-subscriptions`, not in TypeGraphQL.

If you are interested in fixing this, go to https://github.com/apollographql/graphql-subscriptions/issues/178 and create a simple reproduction repo using only ApolloServer (typedefs and resolvers), not TypeGraphQL.
