### ISSUE TITLE
formatArgumentValidationError causing typescript error

### ISSUE THREAD

**Issue by jansselt** [19majkel94/type-graphql#258] opened 2019-02-22 16:13 UTC
Following along with @benawad fantastic tutorial.  On the validation [video](https://www.youtube.com/watch?v=JSo5FtG4Xvk&list=PLN3n1USn4xlma1bBu3Tloe4NyYn9Ko8Gs&index=3).

I'm running into an issue when attempting to use formatArgumentValidationError.

```
import { ApolloServer } from 'apollo-server-express';
import Express from 'express';
import 'reflect-metadata';
import { buildSchema, formatArgumentValidationError } from 'type-graphql';
import { createConnection } from 'typeorm';

import { RegisterResolver } from './modules/user/Register';

const main = async () => {
  await createConnection();

  const schema = await buildSchema({
    resolvers: [RegisterResolver]
  });

  const apolloServer = new ApolloServer({ schema, formatError: formatArgumentValidationError });

  const app = Express();

  apolloServer.applyMiddleware({ app });

  app.listen(4000, () => {
    // tslint:disable-next-line:no-console
    console.log('Server started on http://localhost:4000/graphql');
  });
};

// tslint:disable-next-line:no-floating-promises
main(); 
```

This is resulting in the TS error below

```
$ ts-node-dev --respawn src/index.ts
Using ts-node version 8.0.2, typescript version 3.3.3333
[ERROR] 09:59:16 ⨯ Unable to compile TypeScript:
src/index.ts(16,51): error TS2322: Type '(err: GraphQLError) => { [key: string]: any; }' is not assignable to type '(error: GraphQLError) => GraphQLFormattedError'.
  Type '{ [key: string]: any; }' is missing the following properties from type 'GraphQLFormattedError': message, locations, path
```

I haven't seen anyone else complain of this, so it feels like an issue with my setup.  But I cannot for the life of me figure out why I am getting it while no one else is.

**Comment by vfaramond** [comment] 2019-02-22 17:50
Hi @jansselt, the typings of `formatError` have been updated on version `2.4.3` of `apollo-server-express`. Version `2.4.2` works 👍

**Comment by jansselt** [comment] 2019-02-22 17:59
Alright, will downgrade for now until this is updated to coincide.  Thanks @vfaramond .  Was going crazy.

**Comment by galkin** [comment] 2019-02-23 10:02
@19majkel94, sorry for creating duplicate. Do we plan fix this issue?

**Comment by 19majkel94** [comment] 2019-02-23 10:06
There is a lot of weird type changes in `apollo-server` right now:
https://github.com/apollographql/apollo-server/pull/2346

I will wait for it to settle down and then re-investigate whether it really changed the signature or the API.

**Comment by vfaramond** [comment] 2019-02-23 10:14
In the meantime, this is the custom implementation of `formatError` I use with the last version (2.4.6) of `apollo-server-express`:

```
formatError: (error: GraphQLError): GraphQLFormattedError => {
  if (error.originalError instanceof ApolloError) {
    return error;
  }

  if (error.originalError instanceof ArgumentValidationError) {
    const { extensions, locations, message, path } = error;

    error.extensions.code = 'GRAPHQL_VALIDATION_FAILED';

    return {
      extensions,
      locations,
      message,
      path,
    };
  }

  error.message = 'Internal Server Error';

  return error;
}
```

**Comment by 19majkel94** [comment] 2019-02-23 10:36
Basically, looks like in new ApolloServer the `formatArgumentValidationError` is not needed anymore as the original error is reflected in `extensions`:

```json
{
  "errors": [
    {
      "message": "Argument Validation Error",
      "locations": [
        {
          "line": 22,
          "column": 3
        }
      ],
      "path": [
        "addRecipe"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "validationErrors": [
            {
              "target": {
                "title": "Correct title",
                "description": "Too short description"
              },
              "value": "Too short description",
              "property": "description",
              "children": [],
              "constraints": {
                "length": "description must be longer than or equal to 30 characters"
              }
            }
          ],
          "stacktrace": [
            "Error: Argument Validation Error",
            "    at Object.<anonymous> (F:\\#Projekty\\type-graphql\\src\\resolvers\\validate-arg.ts:29:11)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (F:\\#Projekty\\type-graphql\\node_modules\\tslib\\tslib.js:105:69)",
            "    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by 19majkel94** [comment] 2019-02-23 11:15
I've tested that so I will remove the `formatArgumentValidationError` at all as it's not needed anymore. The first version of ApolloServer, as well as GraphQLYoga, stripped off additional properties, so I had to provide a format helper for that:

```json
{
  "errors": [
    {
      "message": "Argument Validation Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["addRecipe"]
    }
  ],
  "data": null
}
```

**Comment by 19majkel94** [comment] 2019-02-23 11:44
Fixed via 526886c 🔒 

Released in `0.17.0-beta.9` 🎉

**Closed by 19majkel94** 2019-02-23 11:44 UTC
Labels: Bug :bug:, Community  :family_man_girl:

**Comment by Myiyk** [comment] 2019-02-23 18:11
It probably doesn't works for validation in nested objects. 😞

**Comment by 19majkel94** [comment] 2019-02-23 18:13
@Myiyk See #133 - nested inputs are not an instance, so they can't be validated using `class-validator`. It's not a format error fault.

**Comment by git-no** [comment] 2019-04-17 02:52
Error occurs
```
[ERROR] 04:48:40 ⨯ Unable to compile TypeScript:
src/index.ts:7:10 - error TS2305: Module '"../../../../../../../../api-graphql/node_modules/type-graphql/dist"' has no exported member 'formatArgumentValidationError'.

7 import { formatArgumentValidationError } from "type-graphql";
```

with latest packages
```
    "apollo-server-express": "2.4.8",
    "type-graphql": "^0.17.1",
```

**Comment by 19majkel94** [comment] 2019-04-17 05:00
@git-no
Please read this thread once more - this helper was removed.

**Comment by venatir** [comment] 2020-02-12 18:58
You can't simply remove functionality. This is a breaking change.
Please either maintain compatibility with previous minor versions or bump the major.

**Comment by MichalLytek** [comment] 2020-02-12 19:04
@venatir Please check before complaining:

![image](https://user-images.githubusercontent.com/10618781/74367781-bbf3a800-4dd2-11ea-85ac-2c01a5a789c7.png)

It was clearly released as the new major version with a "breaking change" notice 😠

**Comment by galkin** [comment] 2020-02-12 19:55
@venatir, hello my friend.

The package is released as 0.x version, so minor version can have breaking changes. [Proof](https://github.com/npm/node-semver#caret-ranges-123-025-004)

**Comment by MichalLytek** [comment] 2020-02-12 20:09
@galkin Oh, you think it's the source of confusion.

Basically major 0 release has a different semver: 0.MAJOR.MINOR, not patch releases.

![image](https://user-images.githubusercontent.com/10618781/74373033-fada2b80-4ddb-11ea-9a29-59d63742a474.png)

At least that's the way npm handles deps 😉

**Comment by venatir** [comment] 2020-02-12 20:54
My bad. Was aware of the above (0 Major different behaviour), but I read the version from a different package (apollo-server-core) and somehow was convinced this was v2.10.0 :) Please ignore me :)

**Comment by ali26Y** [comment] 2020-12-08 07:46
> In the meantime, this is the custom implementation of `formatError` I use with the last version (2.4.6) of `apollo-server-express`:
> 
> ```
> formatError: (error: GraphQLError): GraphQLFormattedError => {
>   if (error.originalError instanceof ApolloError) {
>     return error;
>   }
> 
>   if (error.originalError instanceof ArgumentValidationError) {
>     const { extensions, locations, message, path } = error;
> 
>     error.extensions.code = 'GRAPHQL_VALIDATION_FAILED';
> 
>     return {
>       extensions,
>       locations,
>       message,
>       path,
>     };
>   }
> 
>   error.message = 'Internal Server Error';
> 
>   return error;
> }
> ```

I can confirm this works however add the following lines to your code:

```
import {  GraphQLError, GraphQLFormattedError } from 'graphql';
import { ApolloError } from 'apollo-server-express';
import { ArgumentValidationError } from 'type-graphql';

....

if (error && error.extensions) {
        error.extensions.code = 'GRAPHQL_VALIDATION_FAILED';
    }

....

return error;
```

**Comment by Adamkaram** [comment] 2021-01-06 08:29
for newcommer from this toutorial u van add this 
import {  GraphQLError, GraphQLFormattedError } from 'graphql';
import { ApolloError } from 'apollo-server-express';
import { ArgumentValidationError } from 'type-graphql';


  const apolloserver = new ApolloServer({
    schema, formatError: (error: GraphQLError): GraphQLFormattedError => {
      if (error && error.extensions) {
        error.extensions.code = 'GRAPHQL_VALIDATION_FAILED';
      }
      return error;
    }
  });

**Comment by akexinad** [comment] 2021-05-06 10:08
I've extended from @Adamkaram 's work and have added this to my code so I can pull out the error messages and add it to an `@ObjectType()` response:

```
import { GraphQLError, GraphQLFormattedError } from "graphql";

type ValidationError = {
    constraints: {
        [key: string]: string;
    }[];
};

const apolloServer = new ApolloServer({
    formatError: (error) => formatArgumentValidationError(error)
});

const formatArgumentValidationError = (
    error: GraphQLError
): GraphQLFormattedError => {
    let validationMessages;

    if (error && error.extensions) {
        validationMessages = error.extensions.exception.validationErrors.map(
            (err: ValidationError) => {
                return Object.entries(err.constraints).map(
                    ([constraintType, message]) => {
                        return {
                            [constraintType]: message
                        };
                    }
                );
            }
        );
    }

    return validationMessages;
};

```
