### ISSUE TITLE
Unexpected "UnhandledPromiseRejectionWarning" for @Args() decorator

### ISSUE THREAD

**Issue by kaluginserg** [19majkel94/type-graphql#278] opened 2019-03-13 14:14 UTC
**Describe the bug**
If I try set wrong type for @Args atribute (without @ArgsType() decorator, for example: CreateUserInputType - _**wrong class!**_), like this:
```typescript
//...
@Query(() => [User])
async users(@Args() data: CreateUserInputType): Promise<User[]> {
    return [];
}
//...
```

I have error message:
```
(node:908) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'target' of undefined
    at params.reduce (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:324:69)
    at Array.reduce (<anonymous>)
    at Function.generateHandlerArgs (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:314:23)
    at handlers.reduce (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:271:28)
    at Array.reduce (<anonymous>)
    at Function.generateHandlerFields (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:264:25)
    at Function.buildRootQueryType (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:233:26)
    at Function.generateFromMetadataSync (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:30:25)
    at Function.<anonymous> (E:\web\server\packages\core\node_modules\type-graphql\dist\schema\schema-generator.js:16:33)
    at Generator.next (<anonymous>)
(node:908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
Maybe error message like "wrong metadata type for argument `data` with `@Args()` decorator..."

**Comment by 19majkel94** [comment] 2019-03-13 18:00
Closing as duplicate of #12 🔒 

> using @Args with @InputType or without @ArgsType

**Closed by 19majkel94** 2019-03-13 18:00 UTC
