### ISSUE TITLE
ObjectType and Boolean(Scalar) in Union type breaks it

### ISSUE THREAD

**Issue by OLDIN** [19majkel94/type-graphql#388] opened 2019-07-30 14:07 UTC
**Describe the bug**
I created union type with ObjectType and Boolean(Scalar) which displays the following error:
`TypeError: Cannot read property 'type' of undefined`

**To Reproduce**
```
@ObjectType()
export class ConditionType {
  @Field(of => ID)
  @Type(() => Number)
  discountId: number;
}

export const ConditionUnion = createUnionType({
  name: 'ConditionTypeUnion',
  types: [ConditionType, Boolean]
});

@ObjectType()
export class TicketTemplateSchema {
  @Field(of => ConditionUnion)
  ticketId: typeof ConditionUnion;
}
```

**Expected behavior**
This should compile and let me query on the union type.

**Logs**
```
[0] TypeError: Cannot read property 'type' of undefined
[0]     at unionMetadata.classTypes.map.objectType (/Users/oldin/projects/tickets-back-end/node_modules/type-graphql/dist/schema/schema-generator.js:64:138)
[0]     at Array.map (<anonymous>)
[0]     at types (/Users/oldin/projects/tickets-back-end/node_modules/type-graphql/dist/schema/schema-generator.js:64:59)
[0]     at resolveThunk (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/definition.js:383:40)
[0]     at defineTypes (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/definition.js:765:15)
[0]     at GraphQLUnionType.getTypes (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/definition.js:735:26)
[0]     at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:307:23)
[0]     at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:295:12)
[0]     at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:330:22)
[0]     at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:295:12) Promise {
[0]   <rejected> TypeError: Cannot read property 'type' of undefined
[0]       at unionMetadata.classTypes.map.objectType (/Users/oldin/projects/tickets-back-end/node_modules/type-graphql/dist/schema/schema-generator.js:64:138)
[0]       at Array.map (<anonymous>)
[0]       at types (/Users/oldin/projects/tickets-back-end/node_modules/type-graphql/dist/schema/schema-generator.js:64:59)
[0]       at resolveThunk (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/definition.js:383:40)
[0]       at defineTypes (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/definition.js:765:15)
[0]       at GraphQLUnionType.getTypes (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/definition.js:735:26)
[0]       at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:307:23)
[0]       at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:295:12)
[0]       at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:330:22)
[0]       at typeMapReducer (/Users/oldin/projects/tickets-back-end/node_modules/graphql/type/schema.js:295:12) }
```

**Enviorment (please complete the following information):**
 - OS: Mac OS
 - Node 10.16.0
 - Package version 0.17.4
 - TypeScript version 3.5.1

**Additional context**
I am doing this within NestJS. I didn't test this without it.
It compiles successfully once I remove the Boolean type.
But I want to create a union type with ObjectType and Boolean.

**Comment by 19majkel94** [comment] 2019-07-30 16:57
GraphQL spec supports union only of object types, not scalars.

Closing as working as intended. 🔒

**Closed by 19majkel94** 2019-07-30 16:57 UTC
