### ISSUE TITLE
Support for Apollo client schema generation

### ISSUE THREAD

**Issue by quentinus95** [19majkel94/type-graphql#291] opened 2019-03-27 15:40 UTC
This may be related to #197.

So Apollo Client now supports client-side schema.
https://blog.apollographql.com/announcing-apollo-client-2-5-c12230cabbb7

Could / does type-graphql support generating client side schema extensions ? It would be awesome!

As always, thanks for your work.

**Comment by quentinus95** [comment] 2019-03-27 15:44
Note that I already share my type-graphql classes with my frontend, the only warning I get is
warning  in ./node_modules/type-graphql/helpers/loadResolversFromGlob.js
Critical dependency: the request of a dependency is an expression

But I guess the question here is how to support the new extend keyword (maybe through class inheritance?).

**Comment by 19majkel94** [comment] 2019-03-27 16:03
Yeah, `apollo-link-state` = Apollo Client 2.5 client-side schema, so it's a duplicate of #197.

You should try `buildTypeDefsAndResolvers` and the dirty hack or webpack alias for `glob` package.

**Closed by 19majkel94** 2019-03-27 16:03 UTC

**Comment by quentinus95** [comment] 2019-04-05 08:48
@19majkel94 thanks for your answer, what about support for the extend keyword?

**Comment by 19majkel94** [comment] 2019-04-05 11:59
@quentinus95 See #228.
If you thinking about extending type from server schema, it might be super tricky with `graphql-js`. Maybe in the future I will support printing arbitrary typeDefs, not the entire printed schema.

**Comment by iEricKoh** [comment] 2019-04-10 12:57
@19majkel94 I am gong to try it with apollo client side schema,  I was wondering is it possible to combine two `typeDefs` together when calling `buildTypeDefsAndResolvers`.

```
// client schema type extend from server schema
export const typeDefs = gql`
  extend type Product {
    selectedOptions: String!
  }
`

// types define by type-graphql
@ObjectType()
export default class Counter {
  @Field()
  value!: number;
}
```

**Comment by 19majkel94** [comment] 2019-04-10 16:47
You can use whatever you want from the broad GraphQL ecosystem, you're not coupled to TypeGraphQL using `buildTypeDefsAndResolvers`:
https://www.apollographql.com/docs/graphql-tools/schema-stitching#adding-resolvers
