### ISSUE TITLE
ObjectType extends does not work

### ISSUE THREAD

**Issue by zuijiaoluo** [19majkel94/type-graphql#209] opened 2018-12-03 15:47 UTC
**Describe the bug**
I wanted to do a simple paging query, but found that ObjectType extends was not possible and the following error occurred, which would not have occurred without inheritance

**To Reproduce**
type.ts
```
@ObjectType()
export class PageInfo {
  @Field({ nullable: true })
  startCursor?: string;

  @Field({ nullable: true })
  endCursor?: string;

  @Field({ nullable: false })
  hasPreviousPage: boolean;

  @Field({ nullable: false })
  hasNextPage: boolean;

  @Field({ nullable: false })
  totalCount: number;
}

@ObjectType()
export class Connection {
  @Field({ nullable: true })
  pageInfo: PageInfo;
}
@ObjectType()
export class TextConnection extends Connection {
  @Field({ nullable: true })
  name: string;
}
```
resolver.ts
```
@Query(returns => TextConnection, { nullable: true })
  async Test() {
    return {
      pageInfo: {
        startCursor: 'string',
        endCursor: 'string',
        hasPreviousPage: true,
        hasNextPage: true,
        totalCount: 0,
      },
      name: "ok"
    };
  }
```
**Expected behavior**
just back true result

**Logs**
<img width="1231" alt="default" src="https://user-images.githubusercontent.com/22735208/49383269-4ebaa080-f753-11e8-9ada-086257934054.png">

**Enviorment (please complete the following information):**
 - OS: mac
 - Node 8.9.1
 - Package version ^0.15.0
 - TypeScript version 3.1.6

**Additional context**

**Comment by 19majkel94** [comment] 2018-12-03 15:51
Looks like a duplicate of #160 😕

**Comment by 19majkel94** [comment] 2018-12-03 17:34
You have to wait 😞 #160 will be fixed by #183

**Closed** 2018-12-03 17:35 UTC
Labels: Duplicate :key:, Question :grey_question:

**Comment by zuijiaoluo** [comment] 2018-12-03 17:37
Thank you. I'll wait for the new version, but I don't know how long it will take. Is there a temporary solution?

**Comment by 19majkel94** [comment] 2018-12-03 17:46
Yes, you just need to return an instance of the class.
You can use a custom helper to be able to use plain objects - see https://github.com/19majkel94/type-graphql/issues/73#issuecomment-386833394

**Comment by MejanH** [comment] 2022-08-16 15:19
facing this issue again. using the latest version.
