### ISSUE TITLE
Is it possible to have multiple same types defined inside the same project?

### ISSUE THREAD

**Issue by vnenkpet** [19majkel94/type-graphql#196] opened 2018-11-13 09:23 UTC
We have a GraphQL server that fetches data from multiple different micro services with GraphQL APIs, which we would like to mock inside the main project and simply instantiate Apollo Servers for each of them. This doesn't work if some types are named the same among them (which is unfortunately our case).

It would be nice if we could add some sort of "instance context" to each decorator so it would tell the decorators to manage these types separately. A  string namespace would be sufficient (and ideally if not specified, it would save it to some sort of "general" namespace so we'd never get conflicts.)

I wonder if this would be a lot of work.

To clarify, the services are not deployed yet so we need a way to mock them and this would be easier than having a separate repository for each of them.

**Comment by 19majkel94** [comment] 2018-11-13 09:53
I'm not sure if it's related to #110 or #156? 😕

**Comment by 19majkel94** [comment] 2018-11-16 17:11
@vnenkpet
Can you describe your problem and proposed solution in more details?
Would #110 or #156 fix your problem?

**Comment by 19majkel94** [comment] 2018-11-18 14:32
There won't be `{context: "schema1"}` for sure.
But you will be able to achieve the same just with proper imports:

```ts
// ./app/schema1/user.type.ts
@ObjectType()
export class User {
  // ...
}

// ./app/schema1/user.resolver.ts
import { User } from "./user.type.ts"
@Resolver()
export default class UserResolver {
  // ...
  @Query(returns => [User])
  users() {
    // ...
  }
}

// ./app/schemas.ts
import Schema1UserResolver from "./schema1/user.resolver.ts"
import Schema2UserResolver from "./schema2/user.resolver.ts"

const schema1 = buildSchemaSync({
  resolvers: [Schema1UserResolver],
});
const schema2 = buildSchemaSync({
  resolvers: [Schema2UserResolver],
});
```

There will be no global metadata leaks, so only the types used by one schema (and it's resolvers) will be emitted.

So closing as a duplicate of #110 🔒

**Closed by 19majkel94** 2018-11-18 14:32 UTC
Labels: Needs More Info :man_shrugging:, Question :grey_question:

**Comment by jeanpfs** [comment] 2019-01-22 17:01
I've tried it that way, but the schemas always work out the same, regardless of the function.

```ts
export async function getAppGraphqlServer() {
  const schema = await buildSchemaSync({
    resolvers: [WalletResolver],
    validate: false,
    authChecker: authChecker,
    emitSchemaFile: "./app-schema.gql"
  });

  return new ApolloServer({
    schema: schema,
    debug: env("GRAPHQL_DEBUG"),
    tracing: env("GRAPHQL_TRACING"),
    context: ({ event, context }) => ({
      headers: event.headers,
      functionName: context.functionName,
      event,
      context
    })
  } as any);
}

export async function getDashboardGraphqlServer() {
  const schema = await buildSchemaSync({
    resolvers: [TransactionTypeResolver],
    validate: false,
    authChecker: authChecker,
    emitSchemaFile: "./dashboard-schema.gql"
  });

  return new ApolloServer({
    schema: schema,
    debug: env("GRAPHQL_DEBUG"),
    tracing: env("GRAPHQL_TRACING"),
    context: ({ event, context }) => ({
      headers: event.headers,
      functionName: context.functionName,
      event,
      context
    })
  } as any);
}

**Comment by 19majkel94** [comment] 2019-01-22 19:40
@jeanpfs 
You need to run two separated node.js processes:
```
node app-server.js
node dashbord-server.js
```

Where the `getXYZGraphqlServer` methods are located in separate files and used independently.

**Comment by jeanpfs** [comment] 2019-01-23 12:58
@19majkel94 
It worked! Thank you!
