### ISSUE TITLE
List of resolvers in buildSchema() overridden by whatever is defined by DI container

### ISSUE THREAD

**Issue by kriskelly** [19majkel94/type-graphql#395] opened 2019-08-12 17:55 UTC
**Describe the bug**

When a resolver is wired up to the dependency injection container passed to `buildSchema()`, that resolver can be left out of the `resolvers` config array, but its queries/mutations will still be defined on the schema.

**To Reproduce**

1) Create a sample resolver
2) Set up a binding in your DI container config
3) Call buildSchema() with a list of resolvers that does not include your sample resolver

The following should be a fully-working example:

```typescript
import "reflect-metadata";
import { Resolver, Query, buildSchema } from "type-graphql";
import { injectable, Container } from "inversify";
import express = require("express");
import { ApolloServer } from "apollo-server-express";
import { createServer } from "http";

@Resolver()
@injectable()
class SearchResolver {
  @Query(returns => String)
  public async search() {
    return "foo";
  }
}

// tslint:disable-next-line: max-classes-per-file
@Resolver()
@injectable()
class MyOtherResolver {
  @Query(returns => String)
  public async foo() {
    return "bar";
  }
}

const bootstrap = async () => {
  const container = new Container();
  container.bind<SearchResolver>(SearchResolver).to(SearchResolver);
  container.bind<MyOtherResolver>(MyOtherResolver).to(MyOtherResolver);

  const app = express();
  const resolvers: any[] = [MyOtherResolver];

  const schema = await buildSchema({
    resolvers,
    container
  });

  const apolloServer = new ApolloServer({ schema });
  apolloServer.applyMiddleware({ app });

  const server = createServer(app);
  server.listen(3000);
};

bootstrap();
```

**Expected behavior**
The `search` query should not be defined on the schema

**Enviorment (please complete the following information):**
 - OS: macOS 10.14 
 - Node v12.7.0
 - Package version v0.17.4
 - TypeScript version 3.52.

**Additional context**

I ran into this while trying to wrap a particular resolver in a feature flag so that it wouldn't show up in the schema while it was still under development. For now my workaround requires also wrapping the DI container definition in a feature flag, but the behavior seems non-intuitive to me. If this is actually expected behavior, it might make sense to make the `resolvers: ` config optional in cases where it's left up to the DI container.

**Comment by 19majkel94** [comment] 2019-08-12 18:38
Duplicate of #110 🔒

**Closed by 19majkel94** 2019-08-12 18:38 UTC
